### ISSUE TITLE
Merge rbmq_thread to development and release new version

### ISSUE THREAD

**Issue by CThuleHansen** [INTO-CPS-Association/fmu-rabbitmq#32]

**Comment by hejersbo** [comment]
I am consolidating rbmq-thread branch in a new branch hejersbo/rbmq-thread. The original rbmq-thread branch had turned into a spaghetti nightmare with duplicate commits and merge commits that really obstructed making any sense of history and making any review almost impossible. I created the hejersbo/rbmq-branch with the goal of rebasing into a smaller set of logically coherent commits, that provides a linear history and is reviewable.

For now the hejersbo/rbmq-thread branch contains everything from the rbmq-thread branch. Still missing is integration of a single commit from the rbmq-priority-queue branch. This is in progress.

The original rbmq-thread branch is deprecated for now - please don't base any new work off on that. 

Also, don't base any work off of the new hejersbo/rbmq-thread branch yet. This branch is being actively rebased, so please wait until its merged into development.

**Comment by hejersbo** [comment]
Branch hejersbo/rbmq-thread has now been consolidated and is ready for merge into development (has been merged and verified locally). I will await doing the final merge until @gitting-around has reviewed the changes in the hejersbo/rbmq-thread branch, since the branch has rebased and squashed commits from both of us. For now, I will leave this issue as code complete and await review from @gitting-around.

**Comment by gitting-around** [comment]
I am ok with the included commits. Go ahead and merge when you can @hejersbo.

**Comment by hejersbo** [comment]
Branch hejersbo/rbmq-thread now merged into devel.

**Comment by hejersbo** [comment]
This issue is completed. Branch is merged and new release made.
