### ISSUE TITLE
Initialization procedure almost impossible?

### ISSUE THREAD

**Issue by CThuleHansen** [INTO-CPS-Association/fmu-rabbitmq#9]
Say three variables need to be defined that arrive in three different messages.

The initialization procedure will get a message(msg1) and use this to determine the starttimeoffset.

This determines a single output for `msg1.id`.
Initialization requires the rest of the variables to be <= starttimeoffset.

So msg2 must have time <= msg1.time.
And msg3 must have time <= msg2.time

So any subsequent value has to be less than the first value received - which most likely will be difficult to achieve.

**Comment by CThuleHansen** [comment]
A better solution would be: Define all ouputs
Select the latest time of all outputs

Keep doing this until timeout / successful check

**Comment by CThuleHansen** [comment]
Set initial to true in fmucontainercore::initialize and keep calculating starttime until a successfull check.

**Comment by clagms** [comment]
If I understand correctly, this is one of the reasons why we should consider the latest timestamp of the messages read during the initialize (and not the minimum as the implementation is currently doing).
I don't think the commit https://github.com/INTO-CPS-Association/fmu-rabbitmq/commit/c4e16e958391df56f241bf8992f3687c96dfa7e4 solves this completely. It is still calculating the minimum timestamp, instead of the maximum timestamp.

Waiting for more data from the network won't solve this problem, because that data may never arrive.

I'm sorry that we did not see this in our last meeting... only now that I'm working on a new iteration of the specification I see that I should not have agreed to change the spec (on this point :p).

To be sure I understand this correctly, here's a more extensive scenario, happening during the initialization.
Suppose the fmu has two outputs, one string and one integer, so it is going to read two types of messages.
It reads the following messages 
```
Type A:  ("a", 09:00), ("b", 09:01), ("c", 09:02)
Type B:  (1, 09:01), (2, 09:02)
```

The FMU function will determine that 09:00 is the start time offset, and convert the messages to:
```
Type A:  ("a", 0), ("b", 1), ("c", 2)
Type B:  (1, 1), (2, 2)
```

Now what are the initial outputs of this FMU for the output B?

The FMU will always block on the first call to initialize on the above example, because it found a future value, and is still waiting for a next value.
Worse: Since the network can drop values, the value that we're looking for may never arrive, unless the FMU uses an interpolation on the future value (which is definitely not recommended here).

@CThuleHansen , @lausdahl , I'll not make changes to the spec for now on this point... One of the reviewers of our paper actually asked why do we take the largest time stamp as our initial timestamp, and it's good that Casper forced us to better explain why.

**Comment by clagms** [comment]
After reading a bit of the code in the master branch, I think this issue is solved.
The code seems to be emptying the incoming lookahead and then selecting the largest timestamp in the current data as the starting time. This is consistent with the spec.
